sub init()
    m.top.functionName = "getProgramDetails"
end sub

sub getProgramDetails()
    result = getJson(m.top.serverUrl + "/api/epg/programs/" + m.top.programId + "/")
    if result <> invalid
        m.top.details = result
    else
        m.top.details = {}
    end if
end sub


function getJson(url as string) as dynamic
    xfer = CreateObject("roUrlTransfer")
    xfer.setUrl(url)
    xfer.SetCertificatesFile("common:/certs/ca-bundle.crt")
    xfer.AddHeader("X-Roku-Reserved-Dev-Id", "")
    xfer.InitClientCertificates()
    xfer.addHeader("Authorization", "Bearer " + m.top.accessToken)
    xfer.addHeader("Accept", "application/json")
    port = CreateObject("roMessagePort")
    xfer.SetMessagePort(port)
    if not xfer.AsyncGetToString()
        return invalid
    end if
    msg = wait(0, port)
    if type(msg) <> "roUrlEvent"
        return invalid
    end if
    if msg.GetResponseCode() < 200 or msg.GetResponseCode() >= 300
        return invalid
    end if
    return ParseJson(msg.GetString())
end function
