sub init()
    m.timeGrid = m.top.findNode("timeGrid")
    m.timeGrid.observeField("channelFocused", "onChannelFocused")
    m.timeGrid.observeField("programSelected", "onProgramSelected")
    m.timeGrid.observeField("programFocused", "onProgramFocused")
    '    m.channelLogo = m.top.findNode("channelLogo")
    '    m.channelName = m.top.findNode("channelName")
    m.programTitle = m.top.findNode("programTitle")
    m.programSubtitle = m.top.findNode("programSubtitle")
    m.programDescription = m.top.findNode("programDescription")
    m.programPoster = m.top.findNode("programPoster")
    m.loadingComplete = false
end sub

sub showGuide()
    if m.top.guideChannels = invalid then return
    now = CreateObject("roDateTime")
    m.timeGrid.contentStartTime = Fix(now.asSeconds() / 3600) * 3600
    buildContent()
    if m.top.guideChannels.count() > 0
        m.timeGrid.setFocus(true)
        m.top.channelSelected = 0
    end if

    m.top.signalBeacon("EPGLaunchComplete")
    m.loadingComplete = true
end sub

sub buildContent()
    content = CreateObject("roSGNode", "ContentNode")
    for each channel in m.top.guideChannels
        channelNode = content.createChild("ContentNode")
        channelNode.title = channel.channelNumber.toStr() + " " + channel.name
        channelNode.hdSmallIconUrl = channel.logoUrl
        channelNode.AddFields(channel)
        addPrograms(channelNode, channel.programs)
    end for
    m.timeGrid.content = content
end sub

sub onChannelFocused()
    if m.timeGrid.channelFocused >= 0 then m.top.channelSelected = m.timeGrid.channelFocused

    updateProgramDetails()
end sub

sub onProgramFocused()
    updateProgramDetails()

    if not m.loadingComplete then return
    if m.timeGrid.programFocusedDetails <> invalid and m.timeGrid.programFocusedDetails.focusStartTime >= m.top.endTime
        m.loadingComplete = false
        m.loadMoreProgramsTask = CreateObject("roSGNode", "LoadMoreProgramsTask")
        m.loadMoreProgramsTask.serverUrl = m.top.serverUrl
        m.loadMoreProgramsTask.accessToken = m.top.accessToken
        m.loadMoreProgramsTask.startTime = m.top.endTime
        m.loadMoreProgramsTask.observeField("programs", "onMoreProgramsLoaded")
        m.loadMoreProgramsTask.control = "run"
    end if
end sub

sub updateProgramDetails()
    channel = m.timeGrid.content.getChild(m.timeGrid.channelFocused)
    if channel = invalid then return
    program = channel.getChild(m.timeGrid.programFocused)
    if program = invalid then return

    m.programTitle.text = program.title

    programSubtitleParts = []

    if program.season <> invalid
        episode = "S" + program.season.ToStr("%02d")

        if program.episode <> invalid
            episode += "E" + program.episode.ToStr("%02d")
        end if

        programSubtitleParts.push(episode)
    end if

    if program.SecondaryTitle <> invalid and program.SecondaryTitle <> ""
        programSubtitleParts.push(program.SecondaryTitle)
    end if

    programSubtitleParts.push(channel.name)

    m.programSubtitle.text = programSubtitleParts.Join(" - ")
    m.programDescription.text = program.description

    if m.getProgramDetailsTask = invalid
        m.getProgramDetailsTask = CreateObject("roSGNode", "GetProgramDetailsTask")
    else
        m.getProgramDetailsTask.control = "stop"
        m.getProgramDetailsTask.unobserveField("details")
    end if

    m.getProgramDetailsTask.programId = program.ProgramId
    m.getProgramDetailsTask.accessToken = m.top.accessToken
    m.getProgramDetailsTask.serverUrl = m.top.serverUrl
    m.getProgramDetailsTask.observeField("details", "onProgramDetailsReturned")
    m.getProgramDetailsTask.control = "run"
end sub

sub onProgramDetailsReturned()
    if m.getProgramDetailsTask <> invalid and
        m.getProgramDetailsTask.details <> invalid and
        m.getProgramDetailsTask.details.icon <> invalid and
        m.getProgramDetailsTask.details.icon <> ""
        m.programPoster.uri = m.getProgramDetailsTask.details.icon
    else
        m.programPoster.uri = invalid
    end if
end sub

sub onMoreProgramsLoaded()
    m.loadMoreProgramsTask.unobserveField("programs")

    if m.loadMoreProgramsTask.endTime = invalid or m.top.endTime = m.loadMoreProgramsTask.endTime
        m.loadingComplete = true
        return
    end if

    for i = 0 to m.timeGrid.content.getChildCount() - 1
        channelNode = m.timeGrid.content.getChild(i)

        if channelNode <> invalid
            programs = m.loadMoreProgramsTask.programs[channelNode.tvgId.ToStr()]
            addPrograms(channelNode, programs)
        end if
    end for

    m.top.endTime = m.loadMoreProgramsTask.endTime
    m.loadingComplete = true
end sub

sub onProgramSelected()
    if m.timeGrid.channelFocused >= 0 then m.top.channelActivated = m.timeGrid.channelFocused
end sub

sub focusGuide()
    m.timeGrid.setFocus(true)
end sub

sub addPrograms(channelNode as object, programs as object)
    if programs = invalid then return

    for each program in programs
        program.startSeconds = isoToSeconds(program.start_time)
        program.endSeconds = isoToSeconds(program.end_time)
    end for

    programs.SortBy("startSeconds")

    for each program in programs
        programNode = channelNode.createChild("ContentNode")
        programNode.title = program.title
        programNode.playStart = program.startSeconds
        programNode.playDuration = program.endSeconds - program.startSeconds
        programNode.SecondaryTitle = program.sub_title
        programNode.description = program.description
        programNode.ProgramID = program.id.ToStr()
        programNode.AddFields({ season: program.season, episode: program.episode })
    end for
end sub

function isoToSeconds(value as dynamic) as integer
    if value = invalid or value = "" then return 0
    dateTime = CreateObject("roDateTime")
    dateTime.fromISO8601String(value)
    return dateTime.asSeconds()
end function
