sub init()
    m.top.observeField("setup","setupSignInPage")
    m.signInButton = m.top.findNode("signInButton")
    m.serverUrlField = m.top.findNode("signinURL")
    m.usernameField = m.top.findNode("signinUsername")
    m.passwordField = m.top.findNode("signinPassword")
    m.keyboardDialog = m.top.findNode("signinKeyboard")
    m.keyboardDialog.observeFieldScoped("buttonSelected", "dismissDialog")
    m.keyboardDialog.observeFieldScoped("text", "handleTextEdit")

    m.signInButton.observeField("buttonSelected", "onSignInButtonSelected")

    m.selectedObj = "url"
end sub

sub setupSignInPage()
    if m.serverUrlField.text = ""
        m.serverUrlField.setFocus(true)
    else if m.usernameField.text = ""
        m.selectedObj = "username"
        m.usernameField.setFocus(true)
    else if m.passwordField = ""
        m.selectedObj = "password"
        m.passwordField.setFocus(true)
    end if
end sub

sub setUpEditServerUrl()
    m.keyboardDialog.textEditBox.secureMode = false
    m.keyboardDialog.keyboardDomain = "generic"
    m.keyboardDialog.title = "Dispatcharr URL entry"
    m.keyboardDialog.message = ["Enter your Dispatcharr server URL"]
    m.keyboardDialog.buttons = ["OK"]
    m.keyboardDialog.textEditBox.hintText = "Enter a valid URL..."
    m.keyboardDialog.textEditBox.setFocus(true)
    m.keyboardDialog.text = m.serverUrlField.text
end sub

sub setUpEditUsername()
    m.keyboardDialog.textEditBox.secureMode = false
    m.keyboardDialog.keyboardDomain = "alphanumeric"
    m.keyboardDialog.title = "Username entry"
    m.keyboardDialog.message = ["Enter your Dispatcharr username"]
    m.keyboardDialog.buttons = ["OK"]
    m.keyboardDialog.textEditBox.hintText = "Enter a valid username..."
    m.keyboardDialog.textEditBox.setFocus(true)
    m.keyboardDialog.text = m.usernameField.text
end sub

sub setupEditPassword()
    m.keyboardDialog.keyboardDomain = "password"
    m.keyboardDialog.textEditBox.secureMode = true

    m.keyboardDialog.title = "Password entry"
    m.keyboardDialog.message = ["The password is 8 or more characters"]
    m.keyboardDialog.buttons = ["OK"]
    m.keyboardDialog.textEditBox.hintText = "Create or enter a password..."
    m.keyboardDialog.textEditBox.setFocus(true)
    m.keyboardDialog.text = m.passwordField.text
end sub

sub handleTextEdit()
    if m.selectedObj = "url"
        m.serverUrlField.text = m.keyboardDialog.text
    else if m.selectedObj = "password"
        m.passwordField.text = m.keyboardDialog.text
    else if m.selectedObj = "username"
        m.usernameField.text = m.keyboardDialog.text
    end if
end sub

sub dismissDialog()
    m.keyboardDialog.close = true

    if m.selectedObj = "url"
        m.serverUrlField.setFocus(true)
    else if m.selectedObj = "password"
        m.passwordField.setFocus(true)
    else if m.selectedObj = "username"
        m.usernameField.setFocus(true)
    end if

    m.keyboardDialog.visible = false
end sub

sub onSignInButtonSelected()
    returnToMainScene()
end sub

sub returnToMainScene()
    scene = m.top.getScene()
    scene.serverUrl = m.serverUrlField.text
    scene.username = m.usernameField.text
    scene.password = m.passwordField.text
    m.top.visible = false
    scene.signInComplete = true
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    handled = false

    if press 
        if key = "back" 
            returnToMainScene()
        else if key = "down"
            if m.selectedObj = "url"
                m.passwordField.active = false
                m.usernameField.setFocus(true)
                m.usernameField.active = true
                m.selectedObj = "username"
            else if m.selectedObj = "username"
                m.usernameField.active = false
                m.passwordField.setFocus(true)
                m.passwordField.active = true
                m.selectedObj = "password"
            else if m.selectedObj = "password"
                m.passwordField.active = false
                m.signInButton.setFocus(true)
                m.selectedObj = "button"
            end if
        else if key = "up"
            if m.selectedObj = "username"
                m.usernameField.active = false
                m.serverUrlField.setFocus(true)
                m.serverUrlField.active = true
                m.selectedObj = "url"
            else if m.selectedObj = "password"
                m.passwordField.active = false
                m.usernameField.setFocus(true)
                m.usernameField.active = true
                m.selectedObj = "username"
            else if m.selectedObj = "button"
                m.passwordField.setFocus(true)
                m.passwordField.active = true
                m.selectedObj = "password"
            end if
        else if key = "OK"
            if m.selectedObj = "url"
                setUpEditServerUrl()
            else if m.selectedObj = "password"
                setupEditPassword()
            else if m.selectedObj = "username"
                setUpEditUsername()
            end if

            m.keyboardDialog.visible = true
            m.keyboardDialog.setFocus(true)
        end if
    end if

    return handled
end function
